image:
  file: tools/gitpod/gitpod.Dockerfile

ports:
  - port: 6080
    onOpen: open-preview

vscode:
  extensions:
    - ms-vscode.cmake-tools

tasks:
  - before: cp -R tools/gitpod/.vscode . # apply specific vscode settings for gitpod
